added changes to config. added changes to the new_user script to add the groups option

diff --git a/configuration_script_new_user b/configuration_script_new_user
--- a/configuration_script_new_user
+++ b/configuration_script_new_user
@@ -6,13 +6,16 @@ if [[ $EUID -ne 0 ]]; then
 fi
 # checks if script is being run with sudo or as root user. exit if not.
 
+user="TestUser"
 shell="/bin/bash"
 password="BCIT123"
 new_user=0
 base_uid=1000
+group_add=0
 
-user_exists() {
+user_exists() { 
     if grep -q -e "^$1:" /etc/passwd; then
+      # checks if the username given as a argument exists in the /etc/passwd file
         echo "That user already exists"
         exit 3 # Exit because user already exists
     fi
@@ -21,19 +24,18 @@ user_exists() {
 check_uid() {
   while [[ $new_user -eq 0 ]]; do
     if grep -q -e ":$base_uid:" /etc/passwd || grep -e ":$base_uid:" /etc/group; then
-      # checks if base_uid is already used in /etc/passwd
+      # checks if base_uid is already used in /etc/passwd or if a group is already using the desired ID
       base_uid=$(( base_uid + 1 ))
       # if it is there, then add 1 to the uid and try again to check
       echo $base_uid
     else
+      base_gid=$base_uid 
+      echo "Available UID is: $base_uid"
       new_user=1
       # sets to 1 to exit out of the loop after
-      base_gid=$base_uid
-      
-      echo "Available UID is: $base_uid"
     fi
     # checks in /etc/passwd if the UID already exists in the file
-    # if UID already exists, then increment by 1 and check again
+    # if UID already exists, then increment UID by 1 and check again
     # if there is no matching UID, then change new_user to 1 to exit the while loop
     # source: https://man.archlinux.org/man/grep.1
   done
@@ -45,26 +47,51 @@ add_user() {
   # appends the new user information into the /etc/passwd file
   # source: https://stackoverflow.com/questions/7859281/how-to-add-user-with-out-using-useradd-or-similar-command
   echo "Creating your new user"
-  # appendss info of a new user to the /etc/passwd file to create the new user
   mkdir /home/$user
   # creates the home directory of the new user
-  chmod 744 /home/$user
-  # changing permission for the new home directory for the user. giving read,write execute for owner, read for group and others
+  chown "$user:" "$home_dir"
+  # changing ownership of the home directory to the new user created 
   cp -pr /etc/skel /home/$user
   # source: https://man.archlinux.org/man/cp.1
   # source: https://superuser.com/questions/61611/how-to-copy-with-cp-to-include-hidden-files-and-hidden-directories-and-their-con
   echo "$user:x:$base_gid:$user" >> /etc/group
-
+  # adding the user to their default group with the same name as the username
 } 
 
+make_passwd() {
+  echo "$user:$password" | chpasswd
 
-while getopts ":ds:u:" opt; do
+  # source: https://stackoverflow.com/questions/2150882/how-to-automatically-add-user-account-and-password-with-a-bash-script
+  # source: https://man.archlinux.org/man/chpasswd.8
+}
+
+add_group() {
+
+  for group in group_add; do 
+    if ! grep -q $group /etc/group; then
+      # checks that the desired group name actually exists already
+      echo "This group does not exist"
+      exit 3
+    fi
+    group_line=$(grep -q "${group}" /etc/group)
+    # finds the group in the /etc/group file and saves the text line to variable
+    modified_group="${group_line}${user}"
+    # creates a modified new line adding the new user to the group
+    sed -i 's/$group_line/modified_group/g' /etc/group
+    # source: https://askubuntu.com/questions/20414/find-and-replace-text-within-a-file-using-commands
+    # source: https://man.archlinux.org/man/sed.1
+  done
+}
+
+
+while getopts ":g:s:u:" opt; do
   case "${opt}" in
     u)
       user_exists
       # checks if the desired user exists
+
       user=${OPTARG}
-      # allows input for name of user to be created
+      # allows input for naime of user to be created
       check_uid
       # calls function to check which UID is available for the user
       echo "Creating the user $user with UID $base_uid"
@@ -74,14 +101,23 @@ while getopts ":ds:u:" opt; do
       shell=/bin/${OPTARG}
       ;;
 
+    g) 
+      read -a group_add <<< ${OPTARG}
+      ;;
     :)
-      echo "Error: -${OPTARG} requires an argument for packages to install"
-      exit 2
+      if [[ "${OPTARG}" == "u" ]]; then  
+        echo "Error: -${OPTARG} requires a custom user name"
+        exit 2
+      elif [[ "${OPTARG}" == "s" ]]; then
+        echo "Error: -${OPTARG} requires a custom shell"
+        exit 2
+      fi
       # error for when a user puts an option but has no argument with it when it needs one
       ;;
     *)
       echo "Error: Please enter a valid option"
       exit 2
+
       # error for when a user give an option other than -d or -u
   esac
 done
